package org.example.webbrowser;

import javafx.collections.ObservableList;
import javafx.concurrent.Worker;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebHistory;
import javafx.scene.web.WebView;

import java.net.URL;
import java.util.ResourceBundle;

public class WebBrowserController implements Initializable {
    @FXML
    private WebView webView;

    @FXML
    private TextField textField;

    private WebEngine webEngine;
    private WebHistory webHistory;

    // New classes for architecture
    private Browser browser;
    private AddressBar addressBar;
    private WebPage currentWebPage;

    // Local web server for testing
    private WebServer localServer;

    // Chain of Responsibility for HTTP response handling
    private HTTPHandlerChain handlerChain;

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        webEngine = webView.getEngine();

        // Initialize new architecture
        browser = new Browser();
        addressBar = new AddressBar();
        browser.setAddressBar(addressBar);

        // Initialize Chain of Responsibility for HTTP handling
        handlerChain = new HTTPHandlerChain();

        // Initialize local test web server
        initializeLocalServer();

        // Listener for page loading
        webEngine.getLoadWorker().stateProperty().addListener((obs, oldState, newState) -> {
            if (newState == Worker.State.SUCCEEDED) {
                onPageLoaded();
            } else if (newState == Worker.State.FAILED) {
                browser.handleError(500);
            }
        });

        loadPage();
    }

    /**
     * Initializes local test web server
     */
    private void initializeLocalServer() {
        localServer = new WebServer("test.com");

        // Add test resources
        localServer.addResource("index.html");
        localServer.addResource("about.html");
        localServer.addResource("contact.html");

        // Create test page for successful response (200)
        // This is the ONLY page we store on server
        // Error pages (404, 502, 503) are generated by Chain of Responsibility handlers
        WebPage testPage = new WebPage();
        String testHTML = """
            <!DOCTYPE html>
            <html>
            <head>
                <title>Test Server - Success</title>
                <link rel="stylesheet" href="styles/main.css">
            </head>
            <body>
                <h1>Test Server Page</h1>
                <p>This page is served by the local WebServer!</p>
                <p>Status: 200 OK</p>
                <img src="images/test.png" alt="Test">
                <script src="js/app.js"></script>
            </body>
            </html>
            """;
        testPage.setRawHTML(testHTML);
        testPage.parseHTML();
        localServer.addPage(testPage);

        System.out.println("Local WebServer initialized at: " + localServer.getHost());
        System.out.println("Test URLs:");
        System.out.println("  - test.com/index.html (200 OK - served from server)");
        System.out.println("  - test.com/404 (404 Not Found - generated by NotFoundHandler)");
        System.out.println("  - test.com/502 (502 Bad Gateway - generated by BadGatewayHandler)");
        System.out.println("  - test.com/503 (503 Service Unavailable - generated by ServiceUnavailableHandler)");
    }

    public void loadPage() {
        String inputUrl = textField.getText();

        // Check if this is a request to local test server
        if (inputUrl.contains("test.com")) {
            handleLocalServerRequest(inputUrl);
            return;
        }

        // Use AddressBar for validation
        if (addressBar.validateURL(inputUrl)) {
            // Form full URL with protocol
            String fullUrl = inputUrl;
            if (!inputUrl.startsWith("http://") && !inputUrl.startsWith("https://")) {
                fullUrl = addressBar.getProtocol() + "://" + inputUrl;
            }

            // Update addressBar
            addressBar.setUrl(fullUrl);

            // Load via WebEngine
            webEngine.load(fullUrl);

            // Also update Browser
            browser.loadPage(fullUrl);

        } else {
            browser.handleError(400);
            System.err.println("Invalid URL: " + inputUrl);
        }
    }

    /**
     * Handles requests to local test server
     *
     * CHAIN OF RESPONSIBILITY PATTERN USAGE:
     * 1. Server creates HTTPResponse with status code
     * 2. Response is passed to HTTPHandlerChain
     * 3. Chain processes response through handlers:
     *    - NotFoundHandler checks: statusCode == 404?
     *    - BadGatewayHandler checks: statusCode == 502?
     *    - ServiceUnavailableHandler checks: statusCode == 503?
     *    - SuccessHandler checks: statusCode == 200?
     * 4. Appropriate handler generates error page or processes success
     */
    private void handleLocalServerRequest(String url) {
        System.out.println("\n=== Local Server Request ===");

        // Form full URL
        String fullUrl = url;
        if (!url.startsWith("http://") && !url.startsWith("https://")) {
            fullUrl = "http://" + url;
        }

        // Create HTTP request (client)
        HTTPRequest request = new HTTPRequest(fullUrl, "GET");
        System.out.println("Client sending request to: " + fullUrl);

        // Server processes request and creates response
        HTTPResponse response;

        // Determine status code based on URL path
        if (url.contains("/404")) {
            // Create 404 response - handler will generate error page
            response = new HTTPResponse();
            response.setStatusCode(404);
            response.setBody(""); // Empty body - handler will fill it
            response.getHeaders().put("Content-Type", "text/html");

        } else if (url.contains("/502")) {
            // Create 502 response - handler will generate error page
            response = new HTTPResponse();
            response.setStatusCode(502);
            response.setBody(""); // Empty body - handler will fill it
            response.getHeaders().put("Content-Type", "text/html");

        } else if (url.contains("/503")) {
            // Create 503 response - handler will generate error page
            response = new HTTPResponse();
            response.setStatusCode(503);
            response.setBody(""); // Empty body - handler will fill it
            response.getHeaders().put("Content-Type", "text/html");
            response.getHeaders().put("Retry-After", "30"); // Suggest retry in 30 seconds

        } else {
            // Normal request - process through server and return 200
            response = localServer.processRequest(request);
        }

        // Server sends response
        localServer.sendResponse(response);

        // Each handler will check if it can handle this status code
        // and either process it or pass to next handler
        handlerChain.process(response);

        // Client processes response (old method for compatibility)
        request.parseResponse(response);
        webEngine.loadContent(response.getBody(), "text/html");

        // Parse page for Proxy pattern (image loading)
        currentWebPage = new WebPage();
        currentWebPage.setRawHTML(response.getBody());
        currentWebPage.parseHTML();
        browser.displayPage(currentWebPage);

        // Log result
        if (response.getStatusCode() == 200) {
            System.out.println("Page loaded successfully from local server");
            System.out.println("Handler used: " + response.getHeaders().get("X-Handled-By"));
            printPageInfo();
        } else {
            System.out.println("Error page displayed with status code: " + response.getStatusCode());
            System.out.println("Handler used: " + response.getHeaders().get("X-Handled-By"));
            System.out.println("Error type: " + response.getHeaders().get("X-Error-Type"));

            // Call browser error handler for additional logging
            browser.handleError(response.getStatusCode());
        }
    }

    /**
     * Called when page successfully loaded
     */
    private void onPageLoaded() {
        try {
            // Get HTML content of loaded page
            String htmlContent = (String) webEngine.executeScript("document.documentElement.outerHTML");

            // Create WebPage and parse HTML
            currentWebPage = new WebPage();
            currentWebPage.setRawHTML(htmlContent);
            currentWebPage.parseHTML();

            // Update current page in Browser
            browser.displayPage(currentWebPage);

            // Output information about loaded resources
            System.out.println("\n=== Page Loaded: " + webEngine.getLocation() + " ===");
            System.out.println("HTML files: " + currentWebPage.getHtmlResources().size());
            System.out.println("CSS files: " + currentWebPage.getCssResources().size());
            System.out.println("JS files: " + currentWebPage.getJsResources().size());
            System.out.println("Images: " + currentWebPage.getImageResources().size());

            // Output details about CSS files
            if (!currentWebPage.getCssResources().isEmpty()) {
                System.out.println("\nCSS Resources:");
                for (CSSFile css : currentWebPage.getCssResources()) {
                    System.out.println("  - " + css.getFileName());
                }
            }

            // Output details about JS files
            if (!currentWebPage.getJsResources().isEmpty()) {
                System.out.println("\nJS Resources:");
                for (JSFile js : currentWebPage.getJsResources()) {
                    System.out.println("  - " + js.getFileName());
                }
            }

            // Output details about images (via Proxy)
            if (!currentWebPage.getImageResources().isEmpty()) {
                System.out.println("\nImage Resources (Proxies):");
                for (IImage img : currentWebPage.getImageResources()) {
                    System.out.println("  - " + img.getFileName() + " [Loaded: " + img.isLoaded() + "]");
                }
            }

        } catch (Exception e) {
            System.err.println("Error parsing page: " + e.getMessage());
        }
    }

    public void goBack() {
        webHistory = webEngine.getHistory();
        ObservableList<WebHistory.Entry> entries = webHistory.getEntries();

        if (webHistory.getCurrentIndex() > 0) {
            webHistory.go(-1);
            String currentUrl = entries.get(webHistory.getCurrentIndex()).getUrl();
            textField.setText(currentUrl);
            addressBar.setUrl(currentUrl);
        }
    }

    public void goForward() {
        webHistory = webEngine.getHistory();
        ObservableList<WebHistory.Entry> entries = webHistory.getEntries();

        if (webHistory.getCurrentIndex() < entries.size() - 1) {
            webHistory.go(1);
            String currentUrl = entries.get(webHistory.getCurrentIndex()).getUrl();
            textField.setText(currentUrl);
            addressBar.setUrl(currentUrl);
        }
    }

    public void reload() {
        webEngine.reload();
    }

    /**
     * Get information about current page
     */
    public void printPageInfo() {
        if (currentWebPage != null) {
            System.out.println("\n=== Current Page Info ===");
            System.out.println("URL: " + addressBar.getUrl());
            System.out.println("Protocol: " + addressBar.getProtocol());
            System.out.println("Total HTML files: " + currentWebPage.getHtmlResources().size());
            System.out.println("Total CSS files: " + currentWebPage.getCssResources().size());
            System.out.println("Total JS files: " + currentWebPage.getJsResources().size());
            System.out.println("Total Images: " + currentWebPage.getImageResources().size());
        } else {
            System.out.println("No page loaded yet");
        }
    }
}