(function(){'use strict';var n=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function q(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=q(this);function t(a,b){if(b)a:{var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var g=a[d];if(!(g in c))break a;c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&p(c,a,{configurable:!0,writable:!0,value:b})}}var v;
if(typeof Object.setPrototypeOf=="function")v=Object.setPrototypeOf;else{var w;a:{var x={a:!0},y={};try{y.__proto__=x;w=y.a;break a}catch(a){}w=!1}v=w?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var z=v;function A(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function B(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:A(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function C(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function D(a){return a instanceof Array?a:C(B(a))}function E(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var F=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var g in d)E(d,g)&&(a[g]=d[g])}return a};t("Object.assign",function(a){return a||F});
t("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+g++,k)}function c(k,l){this.g=k;p(this,"description",{configurable:!0,writable:!0,value:l})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",g=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return G(A(this))}});return a});function G(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
t("WeakMap",function(a){function b(f){this.g=(e+=Math.random()+1).toString();if(f){f=B(f);for(var h;!(h=f.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(f){var h=typeof f;return h==="object"&&f!==null||h==="function"}function g(f){if(!E(f,l)){var h=new c;p(f,l,{value:h})}}function k(f){var h=Object[f];h&&(Object[f]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&g(m);return h(m)})}if(function(){if(!a||!Object.seal)return!1;try{var f=Object.seal({}),h=Object.seal({}),
m=new a([[f,2],[h,3]]);if(m.get(f)!=2||m.get(h)!=3)return!1;m.delete(f);m.set(h,4);return!m.has(f)&&m.get(h)==4}catch(u){return!1}}())return a;var l="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var e=0;b.prototype.set=function(f,h){if(!d(f))throw Error("Invalid WeakMap key");g(f);if(!E(f,l))throw Error("WeakMap key fail: "+f);f[l][this.g]=h;return this};b.prototype.get=function(f){return d(f)&&E(f,l)?f[l][this.g]:void 0};b.prototype.has=function(f){return d(f)&&E(f,
l)&&E(f[l],this.g)};b.prototype.delete=function(f){return d(f)&&E(f,l)&&E(f[l],this.g)?delete f[l][this.g]:!1};return b});
t("Map",function(a){function b(){var e={};return e.h=e.next=e.head=e}function c(e,f){var h=e[1];return G(function(){if(h){for(;h.head!=e[1];)h=h.h;for(;h.next!=h.head;)return h=h.next,{done:!1,value:f(h)};h=null}return{done:!0,value:void 0}})}function d(e,f){var h=f&&typeof f;h=="object"||h=="function"?k.has(f)?h=k.get(f):(h=""+ ++l,k.set(f,h)):h="p_"+f;var m=e[0][h];if(m&&E(e[0],h))for(e=0;e<m.length;e++){var u=m[e];if(f!==f&&u.key!==u.key||f===u.key)return{id:h,list:m,index:e,entry:u}}return{id:h,
list:m,index:-1,entry:void 0}}function g(e){this[0]={};this[1]=b();this.size=0;if(e){e=B(e);for(var f;!(f=e.next()).done;)f=f.value,this.set(f[0],f[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var e=Object.seal({x:4}),f=new a(B([[e,"s"]]));if(f.get(e)!="s"||f.size!=1||f.get({x:4})||f.set({x:4},"t")!=f||f.size!=2)return!1;var h=f.entries(),m=h.next();if(m.done||m.value[0]!=e||m.value[1]!="s")return!1;m=h.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!h.next().done?!1:!0}catch(u){return!1}}())return a;var k=new WeakMap;g.prototype.set=function(e,f){e=e===0?0:e;var h=d(this,e);h.list||(h.list=this[0][h.id]=[]);h.entry?h.entry.value=f:(h.entry={next:this[1],h:this[1].h,head:this[1],key:e,value:f},h.list.push(h.entry),this[1].h.next=h.entry,this[1].h=h.entry,this.size++);return this};g.prototype.delete=function(e){e=d(this,e);return e.entry&&e.list?(e.list.splice(e.index,1),e.list.length||delete this[0][e.id],e.entry.h.next=e.entry.next,
e.entry.next.h=e.entry.h,e.entry.head=null,this.size--,!0):!1};g.prototype.clear=function(){this[0]={};this[1]=this[1].h=b();this.size=0};g.prototype.has=function(e){return!!d(this,e).entry};g.prototype.get=function(e){return(e=d(this,e).entry)&&e.value};g.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};g.prototype.keys=function(){return c(this,function(e){return e.key})};g.prototype.values=function(){return c(this,function(e){return e.value})};g.prototype.forEach=
function(e,f){for(var h=this.entries(),m;!(m=h.next()).done;)m=m.value,e.call(f,m[1],m[0],this)};g.prototype[Symbol.iterator]=g.prototype.entries;var l=0;return g});t("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(e){return e};var g=[],k=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof k=="function"){b=k.call(b);for(var l=0;!(k=b.next()).done;)g.push(c.call(d,k.value,l++))}else for(k=b.length,l=0;l<k;l++)g.push(c.call(d,b[l],l));return g}});
t("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)E(b,d)&&c.push([d,b[d]]);return c}});function H(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
t("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=H(this,b,"startsWith"),g=d.length,k=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var l=0;l<k&&c<g;)if(d[c++]!=b[l++])return!1;return l>=k}});t("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
t("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var g=d.length;c=c||0;for(c<0&&(c=Math.max(c+g,0));c<g;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}});t("String.prototype.includes",function(a){return a?a:function(b,c){return H(this,b,"includes").indexOf(b,c||0)!==-1}});
function I(a,b){a instanceof String&&(a+="");var c=0,d=!1,g={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};g[Symbol.iterator]=function(){return g};return g}t("Array.prototype.entries",function(a){return a?a:function(){return I(this,function(b,c){return[b,c]})}});
t("Object.fromEntries",function(a){return a?a:function(b){var c={};if(!(Symbol.iterator in b))throw new TypeError(""+b+" is not iterable");b=b[Symbol.iterator].call(b);for(var d=b.next();!d.done;d=b.next()){d=d.value;if(Object(d)!==d)throw new TypeError("iterable for fromEntries should yield objects");c[d[0]]=d[1]}return c}});t("Array.prototype.keys",function(a){return a?a:function(){return I(this,function(b){return b})}});
t("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)E(b,d)&&c.push(b[d]);return c}});function J(a){var b=K;if(!L(a)){var c,d;b=(d=(c=typeof b==="function"?b():b)==null?void 0:c.concat("\n"))!=null?d:"";throw Error(b+String(a));}}function M(a){a.D=!0;return a}var K=void 0;var N=M(function(a){return typeof a==="number"}),O=M(function(a){return typeof a==="string"}),P=M(function(a){return!!a&&(typeof a==="object"||typeof a==="function")});function Q(a){return R(M(function(b,c){return b===void 0?!0:a(b,c)}))}function R(a){a.u=!0;return a};var aa=new Map([["module","module_name"],["moduleHeadline","section_header"],["index","current_index"],["content","click_text"],["url","click_url"]]);var ba={B:"nav_tier",A:"component_interaction",C:"target_index"};var S={},L=function(a){return M(function(b){if(!P(b))return!1;for(var c=B(Object.entries(a)),d=c.next();!d.done;d=c.next()){var g=B(d.value);d=g.next().value;g=g.next().value;if(!(d in b)){if(g.u===!0)continue;return!1}if(!g(b[d]))return!1}return!0})}((S.nav_tier=Q(O),S.component_interaction=Q(O),S.target_index=Q(N),S),"ExtraEventParams");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function T(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};function U(a,b,c){this.shouldRedactPii=c=c===void 0?!1:c;this.l=a;c&&(this.shouldRedactPii=c);a=this.l;var d=b===void 0?20:b;b={};c={};for(var g,k,l=0;a&&l<=d;){var e=ca(a),f=Object.assign({},e);e=e["data-tracking-extra-context"];f=(delete f["data-tracking-extra-context"],f);b=Object.assign({},f,b);e&&Object.keys(e).length>0&&(c=Object.assign({},e,c));!g&&a.hasAttribute("data-tracking-target")&&(g=a);if(a.hasAttribute("data-tracking-module")){k=a;break}a=a.parentElement;l++}a={};Object.assign(b,c&&
Object.keys(c).length>0?(a["data-tracking-extra-context"]=c,a):{});g=B([g,k,b]);this.m=g.next().value;this.o=g.next().value;this.g=g.next().value;this.m&&(this.v=this.j())}
U.prototype.j=function(){var a;var b=((a=this.g)==null?void 0:a["data-tracking-module"])||"(not found)";a:{var c;if(a=(c=this.g)==null?void 0:c["data-tracking-module-headline"])var d=a;else{if(this.o&&(c=(d=this.o)==null?void 0:d.querySelector("h1, h2, h3"),c instanceof HTMLElement&&c.textContent)){d=T(c.textContent);break a}d="(not found)"}}return{module:b,moduleHeadline:d}};
function ca(a){var b={};a=B(Array.from(a.attributes));for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.name.startsWith("data-tracking-"))if(c.name!=="data-tracking-extra-context")b[c.name]=c.value;else{var d=void 0;try{d=JSON.parse(c.value)}catch(g){continue}if(typeof d==="object"&&d!==null){d=Object.fromEntries(Object.entries(d).filter(function(g){var k=B(g);g=k.next().value;k=k.next().value;return k===void 0||k===null?!1:Object.values(ba).includes(g)}));try{J(d)}catch(g){continue}b[c.name]=
d}}return b};function V(){U.apply(this,arguments)}V.prototype=n(U.prototype);V.prototype.constructor=V;if(z)z(V,U);else for(var W in U)if(W!="prototype")if(Object.defineProperties){var X=Object.getOwnPropertyDescriptor(U,W);X&&Object.defineProperty(V,W,X)}else V[W]=U[W];
V.prototype.j=function(){var a,b;this.i=((a=this.l)==null?void 0:a.getAttribute("href"))||((b=this.m)==null?void 0:b.getAttribute("href"))||"(not found)";a=this.shouldRedactPii&&/^(tel:|mailto:|sms:)/.test(this.i);var c;a:{b=(c=this.g)==null?void 0:c["data-tracking-target-index"];if(b!==void 0&&(c=Number(b),!isNaN(c)))break a;c=void 0}b=Object;var d=b.assign,g=U.prototype.j.call(this);if(a)var k="[redacted]";else{var l,e=(l=this.g)==null?void 0:l["data-tracking-target-content"];k=e?e:(l=(k=this.l)==
null?void 0:k.textContent)?T(l):"(not found)"}return d.call(b,{},g,{content:k,url:a?this.i.replace(/((?:tel|mailto|sms):)(.*)/g,"$1[redacted]"):this.i},c!==void 0&&{index:c})};window.dataLayer=window.dataLayer||[];function da(){this.config=ea}
function Y(){var a=new da;document.addEventListener("click",function(b){if((b==null?void 0:b.target)instanceof HTMLElement){b=new V(b.target,20,a.config.shouldRedactPii);var c=b.v,d=b.g;if(b.m&&c&&!(Object.keys(c).length<=0)){b=(d==null?void 0:d["data-tracking-target"])||"click_event";if(c.url)a:{var g=a.config.subIdKeyNames;var k=B(c.url.split("?"));k.next();k=C(k);if(k.length){k=new URLSearchParams(k.join("?"));g=B(g);for(var l=g.next();!l.done;l=g.next())if(l=k.get(l.value)){k=l;break a}}k=null}d=
Object.assign({},d==null?void 0:d["data-tracking-extra-context"],k&&{subid:k});k=a.config.clickEventKeyMap;g=new Map;c=B(Object.entries(c));for(l=c.next();!l.done;l=c.next()){var e=B(l.value);l=e.next().value;e=e.next().value;l=k.get(l);e!=null&&l!=null&&g.set(l,e)}c=Object.fromEntries(g);window.dataLayer.push(Object.assign({},{event:b},d,c,{site_id:a.config.siteId,custom_timestamp:Date.now()}))}}})};var fa=document.documentElement.getAttribute("site-id")||"(not found)",Z=document.documentElement.getAttribute("subid-param-name"),ea={siteId:fa,clickEventKeyMap:aa,subIdKeyNames:[].concat(D(Z?[Z]:[]),D(["subid","gmbsrc","mcsubid"])),shouldRedactPii:!0};function ha(){Y()}document.readyState==="interactive"||document.readyState==="complete"?Y():document.addEventListener("DOMContentLoaded",ha);}).call(this);
