(function(){'use strict';var aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},n=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);function q(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&n(c,a,{configurable:!0,writable:!0,value:b})}}var t;
if(typeof Object.setPrototypeOf=="function")t=Object.setPrototypeOf;else{var u;a:{var da={a:!0},v={};try{v.__proto__=da;u=v.a;break a}catch(a){}u=!1}t=u?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var w=t;function x(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function y(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:x(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function z(a){if(!(a instanceof Array)){a=y(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var ea=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)A(d,e)&&(a[e]=d[e])}return a};q("Object.assign",function(a){return a||ea});function fa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
q("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,l){this.g=h;n(this,"description",{configurable:!0,writable:!0,value:l})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");n(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return B(x(this))}});return a});function B(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
q("WeakMap",function(a){function b(g){this.g=(f+=Math.random()+1).toString();if(g){g=y(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}function c(){}function d(g){var k=typeof g;return k==="object"&&g!==null||k==="function"}function e(g){if(!A(g,l)){var k=new c;n(g,l,{value:k})}}function h(g){var k=Object[g];k&&(Object[g]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return k(m)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),k=Object.seal({}),
m=new a([[g,2],[k,3]]);if(m.get(g)!=2||m.get(k)!=3)return!1;m.delete(g);m.set(k,4);return!m.has(g)&&m.get(k)==4}catch(p){return!1}}())return a;var l="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var f=0;b.prototype.set=function(g,k){if(!d(g))throw Error("Invalid WeakMap key");e(g);if(!A(g,l))throw Error("WeakMap key fail: "+g);g[l][this.g]=k;return this};b.prototype.get=function(g){return d(g)&&A(g,l)?g[l][this.g]:void 0};b.prototype.has=function(g){return d(g)&&A(g,
l)&&A(g[l],this.g)};b.prototype.delete=function(g){return d(g)&&A(g,l)&&A(g[l],this.g)?delete g[l][this.g]:!1};return b});
q("Map",function(a){function b(){var f={};return f.h=f.next=f.head=f}function c(f,g){var k=f[1];return B(function(){if(k){for(;k.head!=f[1];)k=k.h;for(;k.next!=k.head;)return k=k.next,{done:!1,value:g(k)};k=null}return{done:!0,value:void 0}})}function d(f,g){var k=g&&typeof g;k=="object"||k=="function"?h.has(g)?k=h.get(g):(k=""+ ++l,h.set(g,k)):k="p_"+g;var m=f[0][k];if(m&&A(f[0],k))for(f=0;f<m.length;f++){var p=m[f];if(g!==g&&p.key!==p.key||g===p.key)return{id:k,list:m,index:f,entry:p}}return{id:k,
list:m,index:-1,entry:void 0}}function e(f){this[0]={};this[1]=b();this.size=0;if(f){f=y(f);for(var g;!(g=f.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var f=Object.seal({x:4}),g=new a(y([[f,"s"]]));if(g.get(f)!="s"||g.size!=1||g.get({x:4})||g.set({x:4},"t")!=g||g.size!=2)return!1;var k=g.entries(),m=k.next();if(m.done||m.value[0]!=f||m.value[1]!="s")return!1;m=k.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!k.next().done?!1:!0}catch(p){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(f,g){f=f===0?0:f;var k=d(this,f);k.list||(k.list=this[0][k.id]=[]);k.entry?k.entry.value=g:(k.entry={next:this[1],h:this[1].h,head:this[1],key:f,value:g},k.list.push(k.entry),this[1].h.next=k.entry,this[1].h=k.entry,this.size++);return this};e.prototype.delete=function(f){f=d(this,f);return f.entry&&f.list?(f.list.splice(f.index,1),f.list.length||delete this[0][f.id],f.entry.h.next=f.entry.next,
f.entry.next.h=f.entry.h,f.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].h=b();this.size=0};e.prototype.has=function(f){return!!d(this,f).entry};e.prototype.get=function(f){return(f=d(this,f).entry)&&f.value};e.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};e.prototype.keys=function(){return c(this,function(f){return f.key})};e.prototype.values=function(){return c(this,function(f){return f.value})};e.prototype.forEach=
function(f,g){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,f.call(g,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var l=0;return e});
q("Set",function(a){function b(c){this.g=new Map;if(c){c=y(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(y([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),h=e.next();if(h.done||h.value[0]!=c||h.value[1]!=c)return!1;h=e.next();return h.done||h.value[0]==c||h.value[0].x!=4||
h.value[1]!=h.value[0]?!1:e.next().done}catch(l){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(h){return c.call(d,h,h,e)})};return b});q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)A(b,d)&&c.push(b[d]);return c}});function C(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
q("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=C(this,b,"startsWith"),e=d.length,h=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var l=0;l<h&&c<e;)if(d[c++]!=b[l++])return!1;return l>=h}});
q("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(f){return f};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var l=0;!(h=b.next()).done;)e.push(c.call(d,h.value,l++))}else for(h=b.length,l=0;l<h;l++)e.push(c.call(d,b[l],l));return e}});q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)A(b,d)&&c.push([d,b[d]]);return c}});
function E(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.entries",function(a){return a?a:function(){return E(this,function(b,c){return[b,c]})}});q("Array.prototype.keys",function(a){return a?a:function(){return E(this,function(b){return b})}});
q("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});q("String.prototype.includes",function(a){return a?a:function(b,c){return C(this,b,"includes").indexOf(b,c||0)!==-1}});
q("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=C(this,b,"endsWith");c===void 0&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;e>0&&c>0;)if(d[--c]!=b[--e])return!1;return e<=0}});q("Array.prototype.values",function(a){return a?a:function(){return E(this,function(b,c){return c})}});
q("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});var ha=new Set(Object.values({H:"adg",I:"aff",J:"cam",K:"exp",L:"gcl",M:"inc"}).filter(function(a){return a!=="exp"}));
function F(a){var b=this;if(!a.toLowerCase().startsWith("v4"))throw Error("subid is not a v4 subid");a=a.split("~");this.G=a.shift()||"";this.l=[];this.parameters={};this.B=[];a.forEach(function(c){if(c.toLowerCase().startsWith("exp-"))b.l.push.apply(b.l,z(c.substring(4).split("|").map(function(h){return h.startsWith("-")?h.substring(1):h})));else{for(var d=y(ha),e=d.next();!e.done;e=d.next())if(e=e.value,c.toLowerCase().startsWith(e+"-")){b.parameters[e]=c.substring(e.length+1);return}b.B.push(c)}})}
function ia(a,b){if(!b)return a;b=(b instanceof Array?b:b.split("|")).map(function(c){return c.startsWith("-")?c.substring(1):c});b=new Set([].concat(z(a.l),z(b)));a.l=Array.from(b).filter(function(c){return c});return a}F.prototype.toString=function(){var a=[this.G];this.l.forEach(function(e){a.push("exp-"+e)});for(var b=y(Object.entries(this.parameters)),c=b.next();!c.done;c=b.next()){var d=y(c.value);c=d.next().value;d=d.next().value;a.push(c+"-"+d)}this.B.forEach(function(e){a.push(e)});return a.join("~")};function I(){return fa.apply(0,arguments).filter(function(a){return a})}I();var ja=I("");I("");var ka=new Map([["",{pageSubid:"hom",ctaSelectorSubidMap:new Map([[".ion-hero-2up ","hr"],[".ion-section-header ","end"]])}],["retail/",{pageSubid:"ret",ctaSelectorSubidMap:new Map([[".ion-hero ","hr"],[".ion-section-header ","end"]])}],["restaurants/",{pageSubid:"rst",ctaSelectorSubidMap:new Map([[".ion-hero ","hr"],[".ion-section-header ","end"]])}],["services/",{pageSubid:"ser",ctaSelectorSubidMap:new Map([[".ion-hero ","hr"],[".ion-section-header ","end"]])}]]);/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function J(a){this.g=a}J.prototype.toString=function(){return this.g};function K(a){this.F=a}function L(a){return new K(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var la=[L("data"),L("http"),L("https"),L("mailto"),L("ftp"),new K(function(a){return/^[^:]*([/?#]|$)/.test(a)})];function M(a){var b=b===void 0?la:b;if(a instanceof J)return a;for(var c=0;c<b.length;++c){var d=b[c];if(d instanceof K&&d.F(a))return new J(a)}}var ma=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function N(a,b){if(b instanceof J)if(b instanceof J)b=b.g;else throw Error("");else b=ma.test(b)?b:void 0;b!==void 0&&(a.href=b)};var na=new Map([["/aunz/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/ca-en/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/in/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/uk/think/marketing-strategies/video/create-great-content/",
"https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/us/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"]]);
function oa(){for(var a=y(na.entries()),b=a.next(),c={};!b.done;c={A:void 0},b=a.next()){var d=y(b.value);b=d.next().value;d=d.next().value;c.A=d;document.querySelectorAll('a[href*="'+b+'"]').forEach(function(e){return function(h){try{try{N(h,M(decodeURI(e.A)))}catch(l){}}catch(l){}}}(c))}try{document.querySelectorAll('a[href*="/think"][href*="-gridwall/"]').forEach(function(e){try{e instanceof HTMLAnchorElement&&e.href&&N(e,M(decodeURI(e.href.replace("-gridwall/","/"))))}catch(h){}})}catch(e){}}
;function O(a){var b;return(b=document.querySelector('meta[name="'+a+'"]'))==null?void 0:b.getAttribute("content")};var pa=new RegExp(/![o0]\d/i);function P(){var a=new URLSearchParams(decodeURIComponent(document.location.search.toLowerCase())),b=a.get("subid")||"",c=a.get("gmbsrc")||"";a=a.get("mcsubid")||"";var d=b.match(pa);return[d?b.split(d[0])[0]+d[0]:b,c,a].filter(String)}function qa(){var a=["-ha","-gdn","-adon"];return P().some(function(b){return a.some(function(c){return b.includes(c)})})}function ra(){window.dataLayer=window.dataLayer||[];return window.dataLayer}
function sa(a){ra().push(Object.assign({},a,{custom_timestamp:Date.now()}))}function Q(a){sa({event:"js_error",message:a})};var ta=new Set("_ga _gl authuser hl gl gclid gad_source gclsrc gmbsrc mcsubid subid suffix".split(" ")),ua=new Set(["suffix"]);function R(a,b){Array.from(a).forEach(function(c){for(var d=new URL(c.href),e=y(b.entries()),h=e.next();!h.done;h=e.next()){var l=y(h.value);h=l.next().value;l=l.next().value;d.searchParams.set(h,l)}N(c,M(decodeURI(d.toString())))})};var va=[{m:'a[href^="https://ads.google.com/start/" i]',i:'a[href^="https://ads.google.com/start/"]'},{m:'a[href^="https://business.google.com" i]:not(a[href*="gmbsrc"])',i:'a[href^="https://business.google.com"]',j:"gmbsrc"},{m:'a[href*="./"]'}];
function wa(){var a=document.location.hostname;a=a===void 0?"":a;var b=[].concat(z(va));a&&b.push({m:'a[href*="'+a+'/" i]:not(a[href*="?continue=" i]):not(a[href*="&continue=" i])',i:'a[href*="'+a+'/"]',j:"continue="});a=b.map(function(d){return d.m}).join(",");try{return Array.from(document.querySelectorAll(a))}catch(d){var c=new Set;b.forEach(function(e){try{Array.from(document.querySelectorAll(e.m)).forEach(function(h){c.add(h)})}catch(h){try{e.i&&Array.from(document.querySelectorAll(e.i)).forEach(function(l){var f;
e.j&&(!e.j||(f=l.href)!=null&&f.includes(e.j))||c.add(l)}),e.i&&Q("ne_links_alt_success: "+e.i+" when excluding: "+e.j)}catch(l){Q("ne_int_links_error: "+l)}}});return Array.from(c)}};function xa(a,b){return a.toLowerCase().startsWith("v4")?ia(new F(a),b.split("|")).toString():a.includes(b)?a:a.includes("~")?a.replace("~",b+"~"):a+b}function T(a,b){return a.includes(b)?a:a+(b.startsWith("-")?"":"-")+b}function ya(){try{document.querySelectorAll('li:has(> a[href*="/essentials/"])').forEach(function(a){a.remove()})}catch(a){}}
function U(a,b,c){this.country=a;this.lang=b;this.experimentIds=c===void 0?"":c;a.toLowerCase()!=="us"&&ya();try{var d;if(((d=document.querySelector("html"))==null?void 0:d.getAttribute("site-id"))==="twg"){var e;(e=document.querySelector(".glue-breadcrumbs"))==null||e.remove()}}catch(k){Q("bgc_subid: error removing breadcrumbs: "+k)}try{oa()}catch(k){Q("bgc_subid: error fixing article links: "+k)}try{if((document.documentElement.dataset.dcsLog||"").startsWith("404"))for(var h=y(document.querySelectorAll('a[href^="./"], a[href*="/us/us/"], a[href*="/uk/uk/"], a[href*="/in/in/"], a[href*="/aunz/aunz/"], a[href*="/ca-en/ca-en/"]')),
l=h.next();!l.done;l=h.next()){var f=l.value,g=f.getAttribute("href");if(g){g=g.replaceAll(/\.\.\//gi,"").replace("./","https://business.google.com/");g=g.replace("/us/us/","/us/").replace("/uk/uk/","/uk/").replace("/in/in/","/in/").replace("/aunz/aunz/","/aunz/").replace("/ca-en/ca-en/","/ca-en/");try{N(f,M(decodeURI(g)))}catch(k){}}}}catch(k){Q("bgc_subid: error fixing 404 page links: "+k)}b=(new URL(document.location.href)).searchParams;a=new URLSearchParams;c=y(b.keys());for(d=c.next();!d.done;d=
c.next())d=d.value,e=d.toLowerCase(),(ta.has(e)||e.startsWith("utm"))&&a.set(e,b.get(d));try{R(wa(),a)}catch(k){Q("bgc_subid: error updating internal links: "+k)}b=y(ua.values());for(c=b.next();!c.done;c=b.next())a.delete(c.value);try{this.g(a)}catch(k){Q("bgc_subid: error updating ctas: "+k)}}
U.prototype.g=function(a){var b=decodeURI(a.get("subid")||""),c=decodeURI(a.get("gmbsrc")||"");b&&a.set("subid",xa(b,this.experimentIds));c&&a.set("gmbsrc",T(c,this.experimentIds));b=new URLSearchParams(a);c=y(document.querySelectorAll("a[href*=ads\\.google\\.com i]"));for(var d=c.next();!d.done;d=c.next()){d=d.value;var e=new URL(d.href),h=void 0;d.href.includes("ads.google.com/signup")&&((h=d.textContent)==null?void 0:h.trim())==="Get started"&&(d.textContent="Start now");d.removeAttribute("target");
h=y(b.entries());for(var l=h.next();!l.done;l=h.next()){var f=y(l.value);l=f.next().value;f=f.next().value;e.searchParams.set(l,f)}h=decodeURI(e.searchParams.get("subid")||"");this.experimentIds&&h&&e.searchParams.set("subid",xa(h,this.experimentIds));N(d,M(decodeURI(e.toString())))}R(document.querySelectorAll("a[href*=analytics\\.google\\.com i]"),a);b=new URLSearchParams(a);c=y(document.querySelectorAll("a[href*=gmbsrc i]"));for(d=c.next();!d.done;d=c.next()){d=d.value;e=new URL(d.href);h=y(b.entries());
for(l=h.next();!l.done;l=h.next())f=y(l.value),l=f.next().value,f=f.next().value,e.searchParams.set(l,f);h=decodeURI(e.searchParams.get("gmbsrc")||"");this.experimentIds&&h&&e.searchParams.set("gmbsrc",T(h,this.experimentIds));N(d,M(decodeURI(e.toString())))}a=new URLSearchParams(a);a.has("mcsubid")||a.set("mcsubid",this.country+"-"+this.lang+"-bgc-mc-web!o3");a.has("hl")||this.lang==="unknown"||a.set("hl",this.lang);a.set("fmp",this.country.toLowerCase()==="us"?"2":"1");a.set("referral","true");
this.experimentIds&&a.set("variant",this.experimentIds);R(document.querySelectorAll("a[href*=mcsubid i], a[href*=merchants\\.google\\.com i]"),a)};var za=new Set(["cbl","cbp","cbt"]),Aa=["a.glue-button--high-emphasis[href*=gmbsrc i]","a.glue-button--high-emphasis[href*=https\\:\\/\\/business\\.google\\.com i]","a[href*=https\\:\\/\\/business\\.google\\.com\\/create i]"],Ba=["a.ion-sign-in-card__bento-pill[href*=gmbsrc i]","a.glue-button--medium-emphasis[href*=gmbsrc i]","a.glue-button--medium-emphasis[href*=https\\:\\/\\/business\\.google\\.com i]"],Ca=new Map([[".glue-header__cta ","nav"],[".ion-global-mega-nav__sub-nav__cta-container ","nav"],
[".glue-header__cta--drawer ","nav"],[".ion-sticky-footer ","mob"]]),Da=new Map([[".glue-header__cta ","sig"],[".ion-global-mega-nav__sub-nav__cta-container ","sig"],[".glue-header__cta--drawer ","sig"]]);function Ea(a,b){var c=new Map;a=y(a.entries());for(var d=a.next(),e={};!d.done;e={v:void 0},d=a.next()){var h=y(d.value);d=h.next().value;h=h.next().value;e.v=d;d=h;e=b.map(function(l){return function(f){return l.v+f}}(e)).join(",");c.set(e,d)}return c}function V(){U.apply(this,arguments)}
V.prototype=aa(U.prototype);V.prototype.constructor=V;if(w)w(V,U);else for(var W in U)if(W!="prototype")if(Object.defineProperties){var Fa=Object.getOwnPropertyDescriptor(U,W);Fa&&Object.defineProperty(V,W,Fa)}else V[W]=U[W];function Ga(){var a=document.location;a=(a.pathname.substring(a.pathname.toLowerCase().indexOf("/business-profile/"))+"/").replace("index.html","").replace(/\/\/$/,"/").split("/business-profile/").pop();return ka.get(a)}
V.prototype.g=function(a){function b(m,p,r,D){var G=new URL(m.href),S=m.href.includes("bgcmhp-sso");e||S||G.searchParams.set("gmbsrc",c.country+"-"+c.lang+"-z-z-z-gmb-"+p+"~bgcmhp-"+h+"_"+r+"-u"+(c.experimentIds?(c.experimentIds.startsWith("-")?"":"-")+c.experimentIds:""));p=y(d.entries());for(r=p.next();!r.done;r=p.next()){var H=y(r.value);r=H.next().value;H=H.next().value;S&&za.has(r)||G.searchParams.set(r,H)}D=y((D==null?void 0:D.entries())||[]);for(p=D.next();!p.done;p=D.next())r=y(p.value),p=
r.next().value,r=r.next().value,S&&za.has(p)||G.searchParams.set(p,r);N(m,M(G.toString()))}var c=this;U.prototype.g.call(this,a);var d=new URLSearchParams(a),e=d.get("gmbsrc");e&&d.set("gmbsrc",T(e,this.experimentIds));d.has("hl")||this.lang==="unknown"||d.set("hl",this.lang);d.set("skipLandingPage","true");d.set("skipPagesList","1");a=Ga()||{};var h=a.pageSubid===void 0?"unk":a.pageSubid;a=a.ctaSelectorSubidMap===void 0?new Map:a.ctaSelectorSubidMap;var l=Ea(new Map([].concat(z(Ca),z(a))),Aa);a=
Ea(Da,Ba);l=y(l);for(var f=l.next(),g={};!f.done;g={o:void 0},f=l.next()){var k=y(f.value);f=k.next().value;k=k.next().value;g.o=k;Array.from(document.querySelectorAll(f)).forEach(function(m){return function(p){b(p,"s-z-u",m.o,new Map([["cbl",m.o],["cbp",h],["cbt","now"]]))}}(g))}a=y(a);g=a.next();for(l={};!g.done;l={u:void 0},g=a.next())f=y(g.value),g=f.next().value,f=f.next().value,l.u=f,Array.from(document.querySelectorAll(g)).forEach(function(m){return function(p){b(p,"l-z-d",m.u,new Map([["cbl",
m.u],["cbp",h],["cbt","sig"]]))}}(l))};var X,Ha=document.documentElement.getAttribute("mte")||"",Y=[].concat(z(new Set([].concat(z(ja),z(Ha.split("|"))).filter(String)))).join("|");qa()&&(Y=Y.replace("-ahpm-0000000174-0000000000","").replace("-ahpm-0000000174-0000000001",""));Y&&document.documentElement.setAttribute("mte",Y);X=Y;var Ia=qa();document.documentElement.getAttribute("subid-param-name")||document.documentElement.setAttribute("subid-param-name","gmbsrc");
var Ja=(O("isEom")||"true")==="true",Ka=(O("dma-sharing-enabled-for-all-cps")||"false")==="true",La={D:Ja,C:Ka},Ma=La.C,Z=La.D||!Ma;(function(){ra().push(arguments)})("consent","default",{ad_storage:Z?"denied":"granted",ad_user_data:Z?"denied":"granted",ad_personalization:Z?"denied":"granted",analytics_storage:"granted",ads_data_redaction:Z?!0:!1,url_passthrough:!0});
var Na,Oa=String((O("isEea")||"true")==="true"),Pa=window.document.documentElement.dataset.garIsEligible==="true",Qa=window.document.documentElement.dataset.garHasCreatedAffiliateId==="true",Ra=window.location.pathname.toLowerCase().endsWith("/referrals/")?Pa?Qa?"eligible":"eligibility_pending":Qa?"eligibility_paused":"ineligible":null;
Na=Object.assign({},{event:"on_pageload",locale:(document.documentElement.hasAttribute("data-root")?"root_":"")+(document.documentElement.getAttribute("locale")||"unknown"),site_id:"gbp",login_status:String(document.documentElement.getAttribute("data-is-logged-in")==="true"),experiments:X||void 0,is_bgc:"true",is_eea:Oa,last_modified_date:document.documentElement.getAttribute("last-modified-date")||document.documentElement.getAttribute("publish-date")||""},Ra&&{referrers_eligibility:Ra},{u_agent:window.navigator.userAgent});
sa(Na);document.querySelector('meta[name="isEom"]')||Q("["+document.documentElement.getAttribute("locale")+(document.documentElement.getAttribute("data-root")?"+root":"")+"] !EOM "+window.location.origin+window.location.pathname);Ia&&Q("org_subs: "+P().join(","));function Sa(){var a=document.documentElement.getAttribute("locale"),b=(a||"unknown").split("_"),c=b[1]||"unknown";b=b[0]||"unknown";try{new V(c,b,X)}catch(d){Q("["+a+"]: "+d.message)}}
document.readyState==="interactive"||document.readyState==="complete"?Sa():document.addEventListener("DOMContentLoaded",Sa);}).call(this);
